account/urls.py
#from django.urls import path
#from account import views
from django.contrib import admin
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),



]

article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>/', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>/', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>/', views.articleDelete, name='articleDelete'),
    path('articleSearch/', views.articleSearch, name='articleSearch'),
    path('articleLike/<int:articleId>/', views.articleLike, name='articleLike'),
    
    path('commentCreate/<int:articleId>/', views.commentCreate, name='commentCreate'),
    path('commentUpdate/<int:commentId>/', views.commentUpdate, name='commentUpdate'),
    path('commentDelete/<int:commentId>/', views.commentDelete, name='commentDelete'),
    
]

jasonn2024/urls.py
from django.contrib import admin
from django.urls import include, path
# from main import views
from django.conf.urls.static import static
from django.conf import settings

# from blog.settings import MEDIA_ROOT
# from django.views.static import serve

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('render.urls')),
                  path('upload_profile/', include('upload_profile.urls', namespace='upload_profile')),
                  path('account/', include('account.urls', namespace='account')),
                  path('article/', include('article.urls', namespace='article')),
                  #    path('upload/', include('upload.urls', namespace='upload')),
                  #    path('main/', include('main.urls', namespace='main')),
                  #    path('main/', include('main.urls')),
                  #    re_path('.*', views.main),
              ] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
#    path('', include('render.urls')),
#    path('', views.index, name='index'),
#    path('main/', include('main.urls')),
    path('about/', views.about, name='about'),
    path('bike/', views.bike, name='bike'),
    path('csstest/', views.csstest, name='csstest'),
    path('django/', views.django, name='django'),
    path('main/', views.main, name='main'),
    path('users/', views.users, name='users'),
]

render/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('', include(('main.urls', 'main'), namespace='main')),
]

upload_profile/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'upload_profile'
urlpatterns = [
#    path('', include(('upload_profile.urls', 'upload_profile'), namespace='upload_profile')),
    path('upload_profile/', views.upload_profile, name='upload_profile'),
#    path('', views.upload_profile, name='upload_profile'),
    path('add/', views.add, name='add'),
    path('detail/', views.detail, name='detail'),

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls.base import reverse
from account.models import User

# def index(request):
#    return render(request, 'main/main.html', {})
#    context = {'like': 'Django 很棒______'}
#    return render(request, 'main/main.html', context)
# this index is no used

def main(request):
    context = {'like': 'Django 很棒棒'}
    return render(request, 'main/main.html', context)

def about(request):
    return render(request, 'main/about.html')

def bike(request):
    return render(request, 'main/bike.html')

def csstest(request):
    return render(request, 'main/csstest.html')

def django(request):
    return render(request, 'main/django.html')

def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(request, '請以管理者身份登入')
            return redirect(reverse('account:login') + '?next=' + request.get_full_path())
        return func(request, *args, **kwargs)

    return auth

def users(request):
    users = User.objects.all()
    return render(request, 'main/users.html', {'users': users})

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}關於{% endblock %}
{% block content %}

    <h2>關於 Jason的部落格</h2>
    <p>歡迎來到Jason的 部落格,你可以到留言版留言<br>
<button type="button" class="btn btn-primary"><a class="text-primary" href="https://jasonn2024.onrender.com">jasonn2024</a></button><br>
3F本機 (admin3 admin333333管理者)  (admin2 admin212345)  (admin admin12345管理者)<br>
1F本機 (admin3 admin333333) (admin2 admin212345管理者) (admin admin12345)<br>
<button type="button" class="btn btn-primary"><a class="text-primary" href="https://jasonn2023.onrender.com">jasonn2023</a></button><br>
python manage.py createsuperuser <br>

    </p>
<button type="button" class="btn btn-primary"><a class="text-primary" href="https://youtu.be/Gxr0IvyReUs">Jason的青春歲月</a></button>
<h5>我的第一个 JavaScript 程序</h5>
<p id="demo">这是一个段落</p>
<button type="button" onclick="displayDate()">显示日期</button>

{% endblock %}
{% block script %}
<script>
function displayDate(){
	document.getElementById("demo").innerHTML=Date();
}
</script>
{% endblock %}

main/templates/main/base.html
<!doctype html>
{% load static %}
<html>
<head>
     <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-GJBZWG4DMS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-GJBZWG4DMS');
</script>
<title>部落格</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}" >
{% block css %}{% endblock %}

</head>

<body>
{% include 'main/menu.html' %}
<div class="container-fluid p-2 bg-primary text-white text-center">
  <h2>部落格 -- {% block heading %}{% endblock %}</h2>
 <h6>
    <!--<h3 style="background-color:Tomato;">-->
    <button type="button" class="btn btn-primary"><a class="text-primary" href="/">Blog</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'main:bike' %}">重機</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'main:about' %}">關於</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'main:csstest' %}">CSS練習</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'main:django' %}">詩詞</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'upload_profile:upload_profile' %}">簽到簿</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'main:users' %}">註冊會員</a></button>
</h6>
</div>
{% block content %}{% endblock %}
<div class="container mt-5">
    <div class="row">

    <div class="col-sm-4">
      <h3>第一欄</h3>
        <img src="{% static 'render/bike.jpg' %}" />
<p class="navbar"><h3>navbar{{ like }}{{ time }}</h3>
<p class="applylarge applyred">applylarg applyred這是多重 Class 的例子。</p>
<b class="special">special同一個選擇器(ex: .btn)</b>可以<i class="special">有不同的 instance(物件)。</i>
    </div>

    <div class="col-sm-4">
      <h3>第二欄</h3>
        <img src="{% static 'render/bike.jpg' %}" />
<p class="navbar"> navbar ID 選擇器在一個 HTML 文件中只能被使用一次，而 Class 選擇器在一個 HTML 文件中可以被使用多次。</p>
<p id="footer">footer 這是用 ID 選擇器(#footer)的例子，選擇器建議盡量用 Class，因為這樣子最靈活。</p>
<p>{{ like }}</p>
<p class="red fancy">This paragraph has red text and "fancy" styling.</p>
    </div>

    <div class="col-sm-4">
      <h3>第三欄</h3>
        <img src="{% static 'render/bike.jpg' %}" />
 <p class="special">special 這是Jason第一次用Django做好的部落格!</p>
 <b class="special">special Class 名稱及 ID 名稱都是對大小寫敏感的。</b>舉例來說，<i class="special">.classone 及 .ClassOne 是代表兩個不同的 Class 選擇器。</i>
 <div class="large">large 這是 DIV 範例。</div>
    </div>

  </div>
</div>

{% for message in messages %}
 <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

main/templates/main/bike.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}Jason的重機世界{% endblock %}
{% block content %}
    <p>歡迎來到Jason的重機世界</p>
<p><img src="{% static 'main/img/bike.jpg' %}" alt=""  width="360" height="540"> <img src="{% static 'main/img/bike2.jpg' %}" alt=""  width="360" height="540"> <img src="{% static 'main/img/bike3.jpg' %}" alt=""  width="360" height="540"></p>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% endblock %}

main/templates/main/csstest.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}Jason的CSS練習{% endblock %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>烘培工坊</title>
    <link rel="stylesheet" href="{% static 'main/css/csstest.css' %}">
</head>
<body>
    <header>
    <button class="menu">&#9776;</button>
    <h1>烘培工坊</h1>
    <nav>
    <ul>
        <li><a href="#">最新消息</a></li>
        <li><a href="#">關於我們</a></li>
        <li><a href="#">門市據點</a></li>
        <li><a href="#">會員專區</a></li>
    </ul>
    </nav>
    </header>
    <main>

    <section class="news">
    <h2>健康穀物麵包新鮮出爐！</h2>
    <p>亞麻的細語、葵花的微風，每一口都是自然的敘事</p>
    <p><a href="#">瞭解更多</a></p>
    </section>

    <section class="slogan">
    <blockquote>" 嚴選天然食材，精湛匠心烘培，<br>讓幸福在每口麵包中的香氣中蔓延 "</blockquote>
    </section>

    <section class="shop">
    <img src="{% static "render/bike.jpg" %}" alt="烘培工坊大安店">
    <div class="info">
    <h2>8月1日大安旗艦店隆重開張！</h2>
    <p>享受花園庭院的悠閒時光，內用座位區美食相伴，<br>
       即日起來店消費加 LINE 好友可獲精緻小點心，等您一同品味！</p>
    </div>
    </section>

    <section class="product">
        <div>
            <img src="{% static "render/bike.jpg" %}" alt="巴黎風法國土司">
            <h3>巴黎風法國土司</h3>
            <p>外皮金黃酥脆，內質鬆軟<br>讓您體驗法式浪漫的味覺享受</p>
        </div>
        <div>
            <img src="{% static "render/bike.jpg" %}" alt="皇家奶油可頌麵包">
            <h3>皇家奶油可頌麵包</h3>
            <p>酥脆口感搭配奶油的濃郁香氣<br>品嘗簡單而純粹的美味</p>
        </div>
        <div>
            <img src="{% static "render/bike.jpg" %}" alt="健康營養全麥土司">
            <h3>健康營養全麥土司</h3>
            <p>全麥製成，口感柔韌紮實<br>天然養分健康首選</p>
        </div>
    </section>
    <section class="newsletter">
        <p>歡迎訂閱烘培工坊電子報，可不定期收到限定優惠喔！</p>
        <form>
            <input type="email" placeholder="請輸入您的 Email" required>
            <button type="submit">送出</button>
        </form>
    </section>
    </main>
    <footer>
        <p>Copyright © 2023 烘培工坊 All Rights Reserved.</p>
    </footer>
</body>
{% endblock %}

main/templates/main/django.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}Jason的詩詞世界{% endblock %}
{% block content %}

    <p>歡迎來到Jason的詩詞世界</p>
<p>
長恨歌
唐代：白居易

漢皇重色思傾國，御宇多年求不得。
楊家有女初長成，養在深閨人未識。
天生麗質難自棄，一朝選在君王側。
回眸一笑百媚生，六宮粉黛無顏色。
春寒賜浴華清池，溫泉水滑洗凝脂。
侍兒扶起嬌無力，始是新承恩澤時。
雲鬢花顏金步搖，芙蓉帳暖度春宵。
春宵苦短日高起，從此君王不早朝。

承歡侍宴無閒暇，春從春遊夜專夜。
後宮佳麗三千人，三千寵愛在一身。
金屋妝成嬌侍夜，玉樓宴罷醉和春。
姊妹弟兄皆列土，可憐光彩生門戶。
遂令天下父母心，不重生男重生女。
驪宮高處入青雲，仙樂風飄處處聞。
緩歌慢舞凝絲竹，盡日君王看不足。
漁陽鼙鼓動地來，驚破霓裳羽衣曲。

九重城闕煙塵生，千乘萬騎西南行。
翠華搖搖行復止，西出都門百餘里。
六軍不發無奈何，宛轉蛾眉馬前死。
花鈿委地無人收，翠翹金雀玉搔頭。
君王掩面救不得，回看血淚相和流。
黃埃散漫風蕭索，雲棧縈紆登劍閣。
峨嵋山下少人行，旌旗無光日色薄。
蜀江水碧蜀山青，聖主朝朝暮暮情。

行宮見月傷心色，夜雨聞鈴腸斷聲。
天鏇地轉回龍馭，到此躊躇不能去。
馬嵬坡下泥土中，不見玉顏空死處。
君臣相顧盡沾衣，東望都門信馬歸。
歸來池苑皆依舊，太液芙蓉未央柳。
芙蓉如面柳如眉，對此如何不淚垂。
春風桃李花開日，秋雨梧桐葉落時。
西宮南內多秋草，落葉滿階紅不掃。(花開日 一作：花開夜；南內 一作：南苑)

梨園弟子白髮新，椒房阿監青娥老。
夕殿螢飛思悄然，孤燈挑盡未成眠。
遲遲鐘鼓初長夜，耿耿星河欲曙天。
鴛鴦瓦冷霜華重，翡翠衾寒誰與共。
悠悠生死別經年，魂魄不曾來入夢。
臨邛道士鴻都客，能以精誠致魂魄。
為感君王輾轉思，遂教方士殷勤覓。
排空馭氣奔如電，升天入地求之遍。

上窮碧落下黃泉，兩處茫茫皆不見。
忽聞海上有仙山，山在虛無縹渺間。
樓閣玲瓏五雲起，其中綽約多仙子。
中有一人字太真，雪膚花貌參差是。
金闕西廂叩玉扃，轉教小玉報雙成。
聞道漢家天子使，九華帳里夢魂驚。
攬衣推枕起徘徊，珠箔銀屏迤邐開。
雲鬢半偏新睡覺，花冠不整下堂來。

風吹仙袂飄飄舉，猶似霓裳羽衣舞。
玉容寂寞淚闌乾，梨花一枝春帶雨。(闌 通：欄；飄飄 一作：飄颻)
含情凝睇謝君王，一別音容兩渺茫。
昭陽殿里恩愛絕，蓬萊宮中日月長。
回頭下望人寰處，不見長安見塵霧。
惟將舊物表深情，鈿合金釵寄將去。
釵留一股合一扇，釵擘黃金合分鈿。
但教心似金鈿堅，天上人間會相見。

臨別殷勤重寄詞，詞中有誓兩心知。
七月七日長生殿，夜半無人私語時。
在天願作比翼鳥，在地願為連理枝。
天長地久有時盡，此恨綿綿無絕期。
</p>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    {% endblock %}

main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}
首頁
<!--<h3 class="bg-info p-3">-->

{% endblock %}
{% block content %}
<section class="slogan">
<br>
<p>這是主要的內容{{ like }}{{ time }}</p>
    </section>
{% endblock %}

main/templates/main/menu.html
<ul id="menu">
  <li><button type="button" class="btn btn-primary"><a href="{% url 'main:main' %}">首頁</a></button></li>
  <li><button type="button" class="btn btn-primary"><a href="{% url 'article:article' %}">留言板</a></button></li>
  <li><button type="button" class="btn btn-primary"><a href="http://127.0.0.1:8000/admin/">admin</a></button></li>
  {% if user.is_authenticated %}
    <li><button type="button" class="btn btn-primary"><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></button></li>
  {% else %}
    <li><button type="button" class="btn btn-primary"><a href="{% url 'account:register' %}">註冊</a></button></li>
    <li><button type="button" class="btn btn-primary"><a href="{% url 'account:login' %}">登入</a></button></li>
  {% endif %}
</ul>

main/templates/main/users.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}
註冊會員
{% endblock %}

{% block content %}
{% for user in users %}
    <p>帳號: {{ user }}, 網址:{{ user.website }}, 住址:{{ user.address }}, 性別:{{ user.sex }}</p>
{% endfor %}
{% endblock %}